"""
vg_gt.py -- ground truth relations defined in VG's ANNOTATION convention.

The first ground truth (in `export_samples.py`) was defined with 3D metric
thresholds: `near` <= 0.5 m, `above`/`under` a 0.15-1.0 m vertical gap with the
host's footprint covering the target, `behind` by true depth order with 2D
overlap in [0.4, 0.9].  Every one of those is geometrically defensible and
every one of them disagrees with how VG was annotated, because a VG annotator
worked from a single photograph with no depth information at all.  Measured
recall reflected exactly that: `on`, whose definition happens to be
2D-compatible, reached 44%, while `above`/`under`/`in` sat at 0.0% and `near` at
2.1%.

So the thresholds here are calibrated against VG's own human annotations --
315642 of them, via `vg_conventions.py` -- and NOT against any model's output.
That distinction is the whole point.  Calibrating to EGTR's predictions would
make the benchmark measure agreement-with-EGTR, and an improvement to EGTR could
then no longer be detected by it; calibrating to human labels leaves the
benchmark measuring the thing we actually care about.

What is kept and what is replaced:

  kept       the 3D derivation, so every emitted relation is TRUE of the scene.
             `above` still requires the subject to really be higher; `behind`
             still requires it to really be farther from the camera.  The 2D
             bands decide which true relations a human would have bothered to
             label, they never invent one.
  replaced   the constraints that encoded a metric notion no annotator applied:
             footprint containment, the gap cap, the overlap floor, the metric
             `near` radius.

Selection is by joint likelihood under the fitted human feature distributions,
capped at VG's measured annotation rate.  Per-feature bands were tried first and
over-generated by a factor of six -- passing five one-dimensional tests
separately is far easier than sitting inside the five-dimensional cloud.

LATER MEASUREMENT, and the reason `vg_pair_prior.py` now exists.  The fitted 2D
distributions were run back over VG's own held-out annotations and asked to
recover the human's label: 55.3% correct against a 68.8% always-say-`on`
baseline, i.e. worse than a constant.  They are nearly identical across
predicates (`above` dy mu -0.175 sd 0.196, `behind` -0.121 sd 0.203, `near`
-0.021 sd 0.220), so both the family competition and the top-10% ranking were
close to arbitrary.  The class pair recovers the same labels at 80.8%.

So the geometry keeps the job it can do -- deciding whether a relation is TRUE --
and the human class-pair statistics take over the two jobs it cannot:

  which pairs are worth annotating   `rank_by="human"` orders by how often
                                     humans relate these two classes at all
  which wording counts as right      handled at match time, see `vg_pair_prior`

Naming is left geometric by default.  Choosing the predicate by class-pair
argmax as well scores higher (R@100 22.2% against 15.9% on `occlusion_ds2`,
exact match) but collapses the ground truth onto `on` and `near` -- `behind`
falls 199 -> 8 and `under` 44 -> 2 -- which makes mR@K unreportable.  Available
as `name_by="human"`; see the note in TASKS.md before using it.
"""

from __future__ import annotations

import json
import math
import os
from typing import Any, Dict, List, Optional, Sequence, Tuple

#: The seven scale-invariant 2D features, and their medians over the VG train
#: split (`python vg_conventions.py --split train`, 315642 human relations).
#: Only listed here for orientation -- the numbers the derivation actually uses
#: live in `vg_prior.json`.
#:
#: dy     signed vertical centre offset / image height, POSITIVE = subject lower
#: dx     absolute horizontal centre offset / image width
#: d2     normalised centre distance
#: cover  fraction of the SUBJECT's box lying inside the object's box
#: below  subject's bottom edge is lower than the object's
#:
#:               n      dy      dx   cover  area_ratio  below
#: on        89932  -0.054   0.083   1.000     0.126     0.00
#: in        18795  -0.029   0.065   0.638     0.424     0.00
#: near      17995  -0.006   0.186   0.215     0.367     0.00
#: above      6522  -0.156   0.082   0.484     0.250     0.00
#: under      4021  +0.163   0.079   0.328     0.451     1.00
#: behind    11524  -0.124   0.168   0.260     0.398     0.00
#: in front   3392  +0.087   0.150   0.447     0.327     1.00
#:
#: Two of these carry most of the signal.  `cover` at 1.000 is what makes `on`
#: the one predicate whose original 3D definition already agreed with VG, hence
#: its 40.7% recall against 0.0% for `above`/`under`.  And `below`, which is
#: exactly 0 for `behind` and exactly 1 for `in front of`, shows the convention
#: is the monocular ground-plane cue: higher in frame reads as further away.
#: Our `behind` used TRUE depth instead -- correct, and only 78% in agreement
#: with what an annotator would have written.

#: Objects smaller than this fraction of the image's linear dimension are not
#: candidates.  VG annotators drew boxes down to sqrt(area) = 0.057 of the frame
#: at the 5th percentile, 0.067 at the 10th; below that nothing was labelled.
#: Note this gate is on the OBJECT set, not on relation participation: measured
#: over VG, objects that appear in a relation are the same size as those that do
#: not (median linear extent 0.196 vs 0.174), so salience decides what gets a box
#: and not what gets an edge.
MIN_LINEAR_EXTENT = 0.06

#: Annotators avoid relating two objects of the SAME class.  Measured over VG
#: train: 9.5% of available pairs in an image are same-class, but only 2.4% of
#: annotated relations are -- a relative propensity of 0.25.  Without this the
#: derivation emits `shelf above shelf` and `cabinet under cabinet`, which are
#: true of the scene (different boards of one shelving unit, different doors of
#: one kitchen run) but are not relations anyone would state.
#:
#: `near` is exempt: at 7.9% it sits close to the 9.5% baseline, so "cup near cup"
#: is something humans do say.
#:
#: Note what is deliberately NOT filtered.  Two large objects looked like a bad
#: pair to relate -- `drawer under cabinet` reads as part-whole rather than
#: spatial -- but humans annotate large-large pairs at 21.8% against a 7.8%
#: baseline, a propensity of 2.79.  They prefer them.  Adding the size filter
#: intuition suggested would have moved AWAY from the convention.
SAME_CLASS_EXEMPT = {"near"}

#: Fraction of an image's available object pairs that a human actually labels.
#: Measured over VG train: a median image has 11 boxed objects (55 unordered
#: pairs) and 5.5 annotated relations.  Our views have FEWER candidates -- median
#: 9 objects, 36 pairs -- yet exhaustive derivation labels 89% of them.
#:
#: The gap is entirely annotation rate, and no feature model closes it: even a cut
#: that rejects half of VG's own annotations still admits 89% of THOR pairs,
#: because an indoor scene is structured enough that almost every pair genuinely
#: looks typical.  What VG leaves out is not untrue, it is unremarked, and which
#: 10% an annotator remarks on is attention -- not recoverable from geometry.
#:
#: So the rate itself becomes the selection criterion: rank candidates by human
#: typicality and keep the most typical 10%.  That still uses only measured human
#: statistics, one for the ordering and one for the cut-off, and it reproduces VG's
#: density (6.8 relations/view against VG's 5.5).
VG_ANNOTATION_RATE = 0.10

#: A loose bound so `near` cannot fire across a whole room.  This is NOT the old
#: metric threshold doing the work -- at 3 m it excludes opposite-wall pairs and
#: nothing else, and the 2D band is what actually selects.
NEAR_MAX_3D_M = 3.0

#: Minimum true vertical separation for `above`/`under`.  Only a sign check with a
#: tolerance for centroid jitter; the magnitude is left entirely to the 2D band,
#: which is where the old 1.0 m cap went wrong.
VERTICAL_MIN_DY_M = 0.05

#: Maximum HORIZONTAL separation for `above`/`under`.  "Above" means one thing is
#: over another, not merely higher than it somewhere else in the room, and nothing
#: in the original derivation required the two to be stacked at all: a plant on a
#: table qualified as `above` a chair standing beside it.  Measured on
#: `occlusion_ds2` the emitted `above` relations sat at a median horizontal
#: separation of 0.74 m and `under` at 0.43 m with a median 2D `cover` of exactly
#: 0.000 -- the subject's box did not touch the object's at all, against VG's
#: `under` mean cover of 0.426.
#:
#: This is a correctness gate, not a recall lever: it removes relations no
#: annotator would have written, and on its own it barely moves the number,
#: because those pairs were not being matched anyway.
VERTICAL_MAX_HORIZONTAL_M = 0.8

#: `above`/`under` and `behind`/`in front of` are inverse readings of ONE fact, so
#: a pair carries exactly one of each family -- and only ONE direction of it.
#: Measured over VG train, an annotator who labelled (i,j) also labelled (j,i)
#: with the inverse predicate just 2-7% of the time:
#:
#:     above  6288 one direction / 234 both      behind  11291 / 233
#:     under  3787 one direction / 234 both      in front 3159 / 233
#:
#: The original ground truth emitted both directions unconditionally (its counts
#: were exactly symmetric: 38 `above` / 38 `under`, 368 / 368), which doubled the
#: denominator on these four predicates against a convention that almost never
#: does so.
#:
#: Which direction?  Not a fixed per-predicate preference -- the underlying rule
#: is that the SMALLER, more salient object becomes the subject, which holds
#: across all four predicates at 66-79% (vertical 74.0%, depth 70.0%, n=25459).
#: That also reproduces VG's marginal skew as a consequence rather than an
#: assumption: small things usually sit on top of big things, so `above` outnumbers
#: `under` 1.6:1 in VG without the rule ever mentioning either word.
#: A pair carries at most one relation from each family, and the families compete
#: on likelihood.  An earlier version ranked them by a hand-written precedence
#: (vertical, then depth, then proximity) and that was actively wrong: because it
#: also emitted only the top entry per unordered pair, `above` shadowed `under`
#: everywhere and `under` came out at zero against `above`'s 3632.
FAMILIES = {
    "vertical": ("above", "under"),
    "depth": ("behind", "in front of"),
    "proximity": ("near", None),
}


def features_2d(sub_box: Sequence[float], obj_box: Sequence[float],
                width: float, height: float) -> Dict[str, float]:
    """
    Same seven descriptors as `vg_conventions.features`, but taking xyxy boxes.

    Kept as a separate function rather than converting at each call site: the VG
    files are COCO xywh and the THOR exports are xyxy, and silently reformatting
    one into the other is how a sign error gets in.
    """
    sx1, sy1, sx2, sy2 = sub_box
    ox1, oy1, ox2, oy2 = obj_box
    sw, sh = max(sx2 - sx1, 1e-6), max(sy2 - sy1, 1e-6)
    ow, oh = max(ox2 - ox1, 1e-6), max(oy2 - oy1, 1e-6)
    scx, scy = (sx1 + sx2) / 2.0, (sy1 + sy2) / 2.0
    ocx, ocy = (ox1 + ox2) / 2.0, (oy1 + oy2) / 2.0

    ix = max(0.0, min(sx2, ox2) - max(sx1, ox1))
    iy = max(0.0, min(sy2, oy2) - max(sy1, oy1))
    inter = ix * iy

    return {
        "dy": (scy - ocy) / height,
        "dx": abs(scx - ocx) / width,
        "d2": math.hypot((scx - ocx) / width, (scy - ocy) / height),
        "cover": inter / (sw * sh),
        "area_ratio": (sw * sh) / (ow * oh),
        "below": 1.0 if sy2 > oy2 else 0.0,
    }


#: Gaussian parameters and log-likelihood percentiles per predicate, fitted to
#: VG's human annotations by `vg_conventions.py`.  Written once, read at import.
PRIOR_PATH = os.path.join(os.path.dirname(os.path.abspath(__file__)), "vg_prior.json")

#: `area_ratio` spans several orders of magnitude (p10 0.021 to p90 2.634 for
#: `above`), so it is modelled in log space; the rest are already roughly
#: symmetric about their means.
LOG_FEATURES = {"area_ratio"}
LIKELIHOOD_FEATURES = ["dy", "dx", "cover", "area_ratio"]

#: Accept a THOR pair only if it is at least as typical of the predicate as this
#: percentile of VG's own annotations for it.  Expressing the cut in percentiles
#: of human data rather than as a raw score keeps it independent of our own
#: density: "as `above`-looking as the 25th-percentile human `above` label" means
#: the same thing whatever THOR produces.
DEFAULT_PERCENTILE = 25

_PRIOR: Optional[Dict[str, Any]] = None


def prior() -> Dict[str, Any]:
    global _PRIOR
    if _PRIOR is None:
        with open(PRIOR_PATH, encoding="utf-8") as handle:
            _PRIOR = json.load(handle)
    return _PRIOR


def log_likelihood(f: Dict[str, float], predicate: str) -> float:
    """
    How typical this box pair is of human `predicate`, up to a constant.

    Independent Gaussians per feature.  The marginal bands this replaced admitted
    a far larger region than the joint distribution occupies -- on 200 reference
    views they produced 29-33 relations per view against VG's 5.5 -- because
    passing five one-dimensional tests separately is much easier than sitting in
    the middle of the five-dimensional cloud.
    """
    spec = prior()[predicate]
    total = 0.0
    for key in LIKELIHOOD_FEATURES:
        value = f[key]
        if key in LOG_FEATURES:
            value = math.log(max(value, 1e-4))
        mu, sd = spec[key]["mu"], max(spec[key]["sd"], 1e-6)
        total += -0.5 * ((value - mu) / sd) ** 2 - math.log(sd)
    p_below = spec["below_p"]
    total += math.log(max(p_below if f["below"] > 0.5 else 1.0 - p_below, 1e-3))
    return total


def typical(f: Dict[str, float], predicate: str, percentile_cut: int = None) -> bool:
    cut = DEFAULT_PERCENTILE if percentile_cut is None else percentile_cut
    return log_likelihood(f, predicate) >= prior()[predicate]["logl"][f"p{cut}"]


def _extent(box: Sequence[float], width: float, height: float) -> float:
    w = max(box[2] - box[0], 0.0) / width
    h = max(box[3] - box[1], 0.0) / height
    return math.sqrt(max(w * h, 0.0))


def candidates(objects: List[Dict[str, Any]], width: float,
               height: float) -> List[Dict[str, Any]]:
    """Objects large enough that a VG annotator would have boxed them."""
    out = []
    for entry in objects:
        box = entry.get("bbox_xyxy")
        if not box:
            continue
        if _extent(box, width, height) < MIN_LINEAR_EXTENT:
            continue
        out.append(entry)
    return out


def _true_vertical(a: Dict[str, Any], b: Dict[str, Any]) -> Optional[float]:
    pa, pb = a.get("position"), b.get("position")
    if not pa or not pb:
        return None
    return pa["y"] - pb["y"]


def _dist3(a: Dict[str, Any], b: Dict[str, Any]) -> Optional[float]:
    pa, pb = a.get("position"), b.get("position")
    if not pa or not pb:
        return None
    return math.dist((pa["x"], pa["y"], pa["z"]), (pb["x"], pb["y"], pb["z"]))


def _box_area(entry: Dict[str, Any]) -> float:
    x1, y1, x2, y2 = entry["bbox_xyxy"]
    return max(x2 - x1, 0.0) * max(y2 - y1, 0.0)


def _horizontal(a: Dict[str, Any], b: Dict[str, Any]) -> Optional[float]:
    pa, pb = a.get("position"), b.get("position")
    if not pa or not pb:
        return None
    return math.hypot(pa["x"] - pb["x"], pa["z"] - pb["z"])


def _proposals(a: Dict[str, Any], b: Dict[str, Any], width: float, height: float,
               cut: int = None,
               vertical_max_horizontal: Optional[float] = VERTICAL_MAX_HORIZONTAL_M,
               ) -> Dict[str, Tuple[str, Dict, Dict, float]]:
    """
    Which relation FAMILIES this pair could carry, one directed relation each.

    The subject is fixed first, by the human rule (smaller box), and only then
    does the geometry pick the predicate.  Doing it in that order is what makes
    the four inverse predicates fall out in VG-like proportions instead of having
    to be balanced by hand.

    Every family must pass a 3D truth check as well as the 2D human band.  The 3D
    check is what keeps this a ground truth rather than a heuristic relabelling: a
    pair can look like `above` in the image and still be rejected because the
    subject is not actually higher.
    """
    subject, obj = (a, b) if _box_area(a) <= _box_area(b) else (b, a)
    f = features_2d(subject["bbox_xyxy"], obj["bbox_xyxy"], width, height)
    out: Dict[str, Tuple[str, Dict, Dict, float]] = {}
    same_class = subject["vg150_class"] == obj["vg150_class"]

    def admit(predicate: str) -> bool:
        if same_class and predicate not in SAME_CLASS_EXEMPT:
            return False
        return typical(f, predicate, cut)

    dy3 = _true_vertical(subject, obj)
    if dy3 is not None and abs(dy3) >= VERTICAL_MIN_DY_M:
        horizontal = _horizontal(subject, obj)
        stacked = (vertical_max_horizontal is None or horizontal is None
                   or horizontal <= vertical_max_horizontal)
        predicate = "above" if dy3 > 0 else "under"
        if stacked and admit(predicate):
            out["vertical"] = (predicate, subject, obj, log_likelihood(f, predicate))

    ds, do = subject.get("distance"), obj.get("distance")
    if ds is not None and do is not None:
        predicate = "behind" if ds > do else "in front of"
        if admit(predicate):
            out["depth"] = (predicate, subject, obj, log_likelihood(f, predicate))

    d3 = _dist3(subject, obj)
    if d3 is not None and d3 <= NEAR_MAX_3D_M and admit("near"):
        out["proximity"] = ("near", subject, obj, log_likelihood(f, "near"))
    return out


def vg_calibrated_relations(objects: List[Dict[str, Any]], width: int, height: int,
                            exclude_pairs: Optional[set] = None,
                            multi_label: bool = False,
                            cut: int = None,
                            rate: Optional[float] = VG_ANNOTATION_RATE,
                            rank_by: str = "human",
                            name_by: str = "geometry",
                            vertical_max_horizontal: Optional[float] =
                            VERTICAL_MAX_HORIZONTAL_M,
                            ) -> List[Dict[str, Any]]:
    """
    Derive geometric relations in VG's annotation convention.

    `exclude_pairs` holds unordered id pairs already carrying an `on`/`in` edge
    from `parentReceptacles`.  VG almost never double-labels a supported pair as
    also `above` or `near` its support, and emitting both would score the model
    twice on one fact.

    `multi_label` keeps every family a pair satisfies instead of the highest
    priority one.  Off by default: an annotator writes one relation per pair, so
    a multi-label ground truth inflates the denominator with restatements of the
    same geometry.

    `rank_by` decides which pairs survive the 10% annotation-rate cut.

      "human"     how often VG's annotators relate these two CLASSES at all.
                  This is the default because the alternative was measured not to
                  work: the geometry score classifies VG's own labels at 55.3%
                  against a 68.8% majority baseline, so ordering by it was close
                  to ordering at random.  Class co-occurrence is the salience
                  signal -- `chair`/`table` is related 1031 times in VG train and
                  `pillow`/`box` never, yet the old ranking emitted five
                  `behind pillow-box` relations.
      "geometry"  the previous behaviour, kept so earlier numbers reproduce.

    `name_by="human"` additionally picks the predicate by class-pair argmax.  It
    scores higher but collapses the ground truth onto `on` and `near`; see the
    module docstring.
    """
    exclude_pairs = exclude_pairs or set()
    present = candidates(objects, width, height)
    relations: List[Dict[str, Any]] = []
    if rank_by == "human" or name_by == "human":
        from vg.vg_pair_prior import p_predicate, relatedness
    else:
        p_predicate = relatedness = None

    for i, a in enumerate(present):
        for b in present[i + 1:]:
            key = frozenset((a["object_id"], b["object_id"]))
            if key in exclude_pairs:
                continue
            families = _proposals(a, b, float(width), float(height), cut,
                                  vertical_max_horizontal)
            if not families:
                continue
            if name_by == "human":
                # The class pair, not the box geometry, decides which of the true
                # readings a human would have written down.
                order = sorted(
                    families,
                    key=lambda name: -p_predicate(families[name][0],
                                                  families[name][1]["vg150_class"],
                                                  families[name][2]["vg150_class"]))
            else:
                # Highest likelihood wins, not a hand-written precedence: an
                # earlier version ranked the families by a fixed precedence and
                # `above` shadowed `under` everywhere.
                order = sorted(families, key=lambda name: -families[name][3])
            chosen = order if multi_label else order[:1]
            for name in chosen:
                predicate, subject, obj, score = families[name]
                s_class, o_class = subject["vg150_class"], obj["vg150_class"]
                relations.append({
                    "subject": s_class,
                    "predicate": predicate,
                    "object": o_class,
                    "subject_id": subject["object_id"],
                    "object_id": obj["object_id"],
                    "annotation": "vg_calibrated",
                    "logl": round(score, 3),
                    "relatedness": relatedness(s_class, o_class) if relatedness else 0,
                    "loose": bool(subject.get("loose") or obj.get("loose")),
                })

    if rate is None:
        return relations
    budget = max(1, int(round(len(present) * (len(present) - 1) / 2 * rate)))
    if rank_by == "human":
        # Additive rather than a strict primary key: class relatedness decides
        # WHICH pairs are worth a human's attention, and within one class pair --
        # a view with three `chair`/`table` instances -- the geometry score still
        # separates the typical instance from the marginal one.
        relations.sort(key=lambda r: -(math.log1p(r["relatedness"]) + r["logl"]))
    else:
        relations.sort(key=lambda r: -r["logl"])
    return relations[:budget]


def support_pairs(relations: List[Dict[str, Any]]) -> set:
    """Unordered id pairs already covered by an `on`/`in` edge."""
    out = set()
    for r in relations:
        if r.get("predicate") in ("on", "in") and not isinstance(r.get("object"), list):
            out.add(frozenset((r["subject_id"], r["object_id"])))
    return out
